import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const SCAN_BOX_SIZE = width * 0.72;

export const COLORS = {
  bg: '#F8FAF8',
  card: '#FFFFFF',
  primary: '#1E5E3A',
  text: '#0F172A',
  textSub: '#64748B',
  border: '#E2E8F0',
  danger: '#EF4444',
  ripe: '#16A34A',
  rotten: '#EF4444',
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAF8' },
  header: {
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    alignItems: 'center',
    backgroundColor: '#0b1f0d',
  },
  headerTitle: { fontSize: 18, fontWeight: '900', color: '#7EE84A', letterSpacing: 1.5 },
  navTabs: { flexDirection: 'row', backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E2E8F0' },
  tabBtn: { flex: 1, paddingVertical: 12, alignItems: 'center' },
  activeTabBtn: { borderBottomWidth: 3, borderBottomColor: '#1E5E3A' },
  tabText: { fontSize: 13, fontWeight: '700', color: '#64748B' },
  activeTabText: { color: '#1E5E3A', fontWeight: '800' },
  body: { flex: 1, padding: 16, backgroundColor: '#F8FAF8' },
  cameraContainer: { flex: 1, borderRadius: 20, overflow: 'hidden', position: 'relative' },
  camera: { flex: 1 },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
  },
  scanBox: {
    width: SCAN_BOX_SIZE,
    height: SCAN_BOX_SIZE,
    position: 'relative',
    backgroundColor: 'transparent',
  },
  corner: { position: 'absolute', width: 24, height: 24, borderColor: '#7EE84A' },
  tl: { top: 0, left: 0, borderTopWidth: 4, borderLeftWidth: 4, borderTopLeftRadius: 8 },
  tr: { top: 0, right: 0, borderTopWidth: 4, borderRightWidth: 4, borderTopRightRadius: 8 },
  bl: { bottom: 0, left: 0, borderBottomWidth: 4, borderLeftWidth: 4, borderBottomLeftRadius: 8 },
  br: { bottom: 0, right: 0, borderBottomWidth: 4, borderRightWidth: 4, borderBottomRightRadius: 8 },
  scanHint: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 24,
    textAlign: 'center',
    letterSpacing: 0.5,
    backgroundColor: 'rgba(14, 47, 26, 0.9)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#7EE84A',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 12,
  },
  fruitTitle: { fontSize: 26, fontWeight: '800', color: '#0F172A' },
  scientific: { fontSize: 14, fontStyle: 'italic', color: '#64748B', marginBottom: 12 },
  statusBadge: { alignSelf: 'flex-start', paddingVertical: 6, paddingHorizontal: 12, borderRadius: 8, marginBottom: 16 },
  statusText: { fontSize: 14, fontWeight: '800', color: '#0F172A' },
  metaRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  metaLabel: { color: '#64748B', fontSize: 14 },
  metaVal: { color: '#0F172A', fontWeight: '700', fontSize: 14 },
  recoBox: {
    marginTop: 10,
    padding: 10,
    backgroundColor: '#F8FAF8',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  recoTitle: { fontSize: 11, color: '#1E5E3A', fontWeight: '800', marginBottom: 2, textTransform: 'uppercase' },
  recoText: { fontSize: 12, color: '#334155', lineHeight: 16 },
  btn: { backgroundColor: '#1E5E3A', paddingVertical: 14, borderRadius: 12, alignItems: 'center', marginTop: 10 },
  btnText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' },
});

export const vendorStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAF8',
  },
  originalHeader: {
    backgroundColor: '#0b1f0d',
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
  },
  headerLeftGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerTitleText: {
    color: '#7EE84A',
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 1.2,
  },
  headerSubtitleText: {
    color: '#A3B899',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 1,
  },
  roleBadgeBtn: {
    backgroundColor: 'rgba(126, 232, 74, 0.12)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(126, 232, 74, 0.3)',
  },
  roleBadgeBtnText: {
    color: '#7EE84A',
    fontSize: 11,
    fontWeight: '800',
  },
  contentBanner: {
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 8,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  pageHeading: {
    fontSize: 26,
    fontWeight: '900',
    color: '#0F172A',
    marginBottom: 2,
  },
  pageSubheading: {
    fontSize: 13,
    color: '#64748B',
    marginBottom: 12,
  },
  searchAndAddRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  searchBarWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAF8',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 12,
    height: 44,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: '#0F172A',
    padding: 0,
  },
  addFruitBtn: {
    backgroundColor: '#1E5E3A',
    borderRadius: 12,
    paddingHorizontal: 16,
    height: 44,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  addFruitBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  filterPillRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 6,
  },
  filterPill: {
    paddingVertical: 7,
    paddingHorizontal: 18,
    borderRadius: 20,
    backgroundColor: '#F1F5F9',
  },
  filterPillActive: {
    backgroundColor: '#D7ECD9',
  },
  filterPillText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748B',
  },
  filterPillTextActive: {
    color: '#1E5E3A',
    fontWeight: '800',
  },
  tableHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 10,
    backgroundColor: '#F8FAF8',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  tableHeaderColText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#94A3B8',
  },
  fruitRowItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    backgroundColor: '#FFFFFF',
  },
  fruitRowNameCol: { flex: 1.2 },
  fruitRowName: { fontSize: 15, fontWeight: '800', color: '#0F172A' },
  fruitRowUnitLabel: { fontSize: 11, color: '#94A3B8', marginTop: 2 },
  fruitRowStockCol: { flex: 1.3 },
  fruitRowStockVal: { fontSize: 14, fontWeight: '800', color: '#1E293B' },
  fruitRowStockSub: { fontSize: 10, color: '#94A3B8', marginBottom: 4 },
  progressBarBg: { height: 4, backgroundColor: '#E2E8F0', borderRadius: 2, width: '85%' },
  progressBarFill: { height: 4, backgroundColor: '#2E8B57', borderRadius: 2 },
  fruitRowPriceCol: { flex: 1 },
  fruitRowPriceVal: { fontSize: 14, fontWeight: '800', color: '#0F172A' },
  fruitRowPriceSub: { fontSize: 10, color: '#94A3B8' },
  fruitRowActionCol: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  actionEditCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#EEF7EE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomNavBar: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    paddingVertical: 6,
    paddingBottom: 10,
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  bottomNavItem: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 4,
    minWidth: 70,
  },
  bottomNavPillActive: {
    backgroundColor: '#D7ECD9',
    paddingHorizontal: 16,
    paddingVertical: 3,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomNavLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748B',
    marginTop: 2,
  },
  bottomNavLabelActive: {
    color: '#1E5E3A',
    fontWeight: '800',
    marginTop: 2,
  },
  editScrollBody: { padding: 16 },
  editCardContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 16,
  },
  editFruitIdentityRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  editFruitNameBox: { flex: 1, marginRight: 10 },
  fieldLabelSmall: { fontSize: 11, fontWeight: '700', color: '#64748B', marginBottom: 6 },
  fruitNameDisplayBox: {
    backgroundColor: '#F8FAF8',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 42,
    justifyContent: 'center',
  },
  dropdownValueText: { fontSize: 15, fontWeight: '800', color: '#0F172A' },
  idTagPill: { backgroundColor: '#F1F5F9', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, alignSelf: 'flex-start' },
  idTagText: { fontSize: 11, color: '#64748B', fontWeight: '700' },
  twoColGrid: { flexDirection: 'row', gap: 12, marginBottom: 12 },
  inputCol: { flex: 1 },
  iconInputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 10,
    paddingHorizontal: 10,
    height: 42,
  },
  iconInputBoxDisabled: { backgroundColor: '#F8FAF8', borderColor: '#E2E8F0' },
  inputIconPrefix: { fontSize: 14, color: '#64748B', marginRight: 6, fontWeight: '700' },
  suffixUnit: { fontSize: 12, color: '#94A3B8', fontWeight: '600', marginLeft: 4 },
  textInputBase: { flex: 1, fontSize: 14, fontWeight: '700', color: '#0F172A', padding: 0 },
  modalTextInput: {
    backgroundColor: '#F8FAF8',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 44,
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 12,
  },
  updateStockSubCard: {
    backgroundColor: '#F7FAF7',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 16,
  },
  updateStockTitle: { fontSize: 13, fontWeight: '800', color: '#0F172A', marginBottom: 10 },
  radioGroupRow: { flexDirection: 'row', gap: 16, marginBottom: 14 },
  radioOption: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  radioDotOuter: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#94A3B8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioDotOuterActive: { borderColor: '#1E5E3A' },
  radioDotInner: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#1E5E3A' },
  radioLabel: { fontSize: 11, fontWeight: '600', color: '#475569' },
  applyStockAdjustmentBtn: {
    backgroundColor: '#1E5E3A',
    borderRadius: 10,
    height: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 10,
  },
  applyStockAdjustmentBtnText: { color: '#FFFFFF', fontWeight: '700', fontSize: 13 },
  stockHistoryHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
  stockHistoryTitleGroup: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  stockHistoryTitle: { fontSize: 14, fontWeight: '800', color: '#0F172A' },
  viewAllText: { fontSize: 12, fontWeight: '700', color: '#1E5E3A' },
  historyTimelineItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  historyItemLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  historyDot: { width: 8, height: 8, borderRadius: 4 },
  historyDotGreen: { backgroundColor: '#16A34A' },
  historyDotRed: { backgroundColor: '#DC2626' },
  historyDateText: { fontSize: 12, fontWeight: '700', color: '#1E293B' },
  historySubText: { fontSize: 10, color: '#64748B' },
  historyWeightText: { fontSize: 12, fontWeight: '700' },
  historyWeightGreen: { color: '#16A34A' },
  historyWeightRed: { color: '#DC2626' },
  bottomActionRow: { flexDirection: 'row', gap: 12, marginTop: 6, marginBottom: 12 },
  cancelBtn: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  cancelBtnText: { fontSize: 14, fontWeight: '700', color: '#475569' },
  saveChangesBtn: {
    flex: 1.3,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#1E5E3A',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  saveChangesBtnText: { fontSize: 14, fontWeight: '800', color: '#FFFFFF' },
  deleteFruitBtn: {
    height: 46,
    borderRadius: 12,
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FCA5A5',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginBottom: 40,
  },
  deleteFruitBtnText: { fontSize: 14, fontWeight: '800', color: '#DC2626' },
  clearHistoryBtn: {
    height: 42,
    borderRadius: 10,
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FCA5A5',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 16,
    marginBottom: 10,
  },
  clearHistoryBtnText: { fontSize: 13, fontWeight: '800', color: '#DC2626' },
  metricCard: {
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 14,
    borderLeftWidth: 5,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 12,
  },
  metricLabel: { fontSize: 11, fontWeight: '800', color: '#64748B', textTransform: 'uppercase' },
  metricValue: { fontSize: 24, fontWeight: '900', color: '#0F172A', marginTop: 4 },
  sectionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 12,
  },
  sectionCardTitle: { fontSize: 15, fontWeight: '800', color: '#0F172A', marginBottom: 10 },
  statusItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  statusItemLabel: { fontSize: 13, color: '#64748B', fontWeight: '600' },
  statusItemVal: { fontSize: 13, color: '#0F172A', fontWeight: '800' },
  progressBarTrack: { width: '100%', height: 7, backgroundColor: '#f1f5f9', borderRadius: 4, overflow: 'hidden', marginTop: 4 },
  saleTxnCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 12,
  },
  saleTxnHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  saleTxnId: { fontSize: 14, fontWeight: '800', color: '#0F172A', fontFamily: 'monospace' },
  saleTxnAmount: { fontSize: 16, fontWeight: '900', color: '#1E5E3A' },
  saleTxnDate: { fontSize: 11, color: '#94A3B8', marginBottom: 8 },
  saleFruitPillRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  saleFruitPill: {
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  saleFruitPillText: { fontSize: 11, fontWeight: '700', color: '#334155' },
  profileOptionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  profileOptionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  profileOptionText: { fontSize: 14, fontWeight: '700', color: '#1E293B' },
});